name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: BluBracket Infrastructure Scan
        run: |
          set -ax
          env
          SOURCE_BRANCH=${GITHUB_REF/refs\/heads\//}
          BLUBRACKET_SERVICE_ENDPOINT=${{ secrets.BLUBRACKET_TENANT }}
          BLUBRACKET_INTEGRATION_KEY=${{ secrets.BLUBRACKET_INTEGRATION_KEY }}
          docker run -v ${GITHUB_WORKSPACE}:/home/blubracket/iac-checker/repo \
          -u $(id -u):$(id -g) \
          blubracket/iac-checker:0.0.4-beta run \
          --blubracket-service-endpoint ${BLUBRACKET_SERVICE_ENDPOINT} \
          --integration-key ${BLUBRACKET_INTEGRATION_KEY} \
          --source-branch ${GITHUB_HEAD_REF:-${SOURCE_BRANCH}} \
          --target-branch ${GITHUB_BASE_REF:-""} \
          --do-not-fail-on-misconfigurations
